### PR TITLE
Bug fix in Holzapfel tangent component

### PR DESCRIPTION
**Pull request by aabrown100-git**
## Current situation
Holzapfel material test case has very slow convergence (https://github.com/SimVascular/svFSIplus/issues/189). This was introduced during material model restructuring (https://github.com/SimVascular/svFSIplus/pull/159). 

## Release Notes 
- Miniscule bug fix in one component of the tangent matrix for the Holzapfel material model

## Testing
test_LV_Holzapfel_passive now displays excellent convergence
```
---------------------------------------------------------------------
 Eq     N-i     T       dB  Ri/R1   Ri/R0    R/Ri     lsIt   dB  %t
---------------------------------------------------------------------
 ST 1-1  3.900e-02  [0 1.000e+00 1.000e+00 8.962e-07]  [84 -45 13]
 ST 1-2  8.100e-02  [-25 5.159e-02 5.159e-02 9.870e-07]  [92 -55 14]
 ST 1-3  1.240e-01  [-74 1.835e-04 1.835e-04 9.218e-07]  [89 -51 12]
 ST 1-4s 2.200e-01  [-194 1.800e-10 1.800e-10 1.448e-03]  [47 -65 13]
```

## Code of Conduct & Contributing Guidelines 
- [x] I agree to follow the [Code of Conduct](https://github.com/SimVascular/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/SimVascular/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aabrown100-git** [comment]
Is there a way to check the LV_Holzapfel_passive output on Github machines to verify proper convergence behavior?

**Comment by mrp089** [comment]
Good idea! You can change the `pytest` argument
https://github.com/SimVascular/svFSIplus/blob/0590d9ad99a67940d1c0dc980b9fe967523487de/.github/workflows/test.yml#L41
to `pytest -rPv --durations=0`

**Comment by aabrown100-git** [comment]
I have confirmed proper convergence behavior on Github machines. Ready to merge.

**Review by mrp089 — APPROVED** [review]

**Comment by mrp089** [comment]
Thanks!

**Pull request merged**
