### PR TITLE
Add shell test cases plate and valve

### PR DESCRIPTION
**Pull request by mrp089**
## Current situation
Shells were added in #75, this PR adds the tests for them. Crossing off one more test in #95.

## Release Notes 
Meshes and setup from https://github.com/vvedula22/svFSI-Tests/tree/master/09-shells, `xml` input files provided by @ktbolt. I also fixed a bug in the error message reporting the number of nodes that are above the tolerance.

## Documentation
None

## Testing
- Verified that `C++` and `FORTRAN` results match by running both solvers and comparing the outputs in ParaView
- Checked that the tests fail by outputting different time steps

## Code of Conduct & Contributing Guidelines 
- [x] I agree to follow the [Code of Conduct](https://github.com/SimVascular/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/SimVascular/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mrp089** [comment]
I'm putting this on draft until #173 has been addressed.

**Comment by mrp089** [comment]
From [Codecov](https://app.codecov.io/gh/SimVascular/svFSIplus/pull/174/indirect-changes):

image

As intended, we brought coverage in `shells.cpp` from 0 to 69.86%!

**Comment by mrp089** [comment]
The original test also had a `NURBS` mesh. @ktbolt, is that currently supported, and should I add tests for that as well?

**Comment by ktbolt** [comment]
@mrp089 NURBS are not supported.

**Review by MatteoSalvador — APPROVED** [review]

**Pull request merged**
