### PR TITLE
PETSc and Trilinos interface

### PR DESCRIPTION
**Pull request by dcodoni**
## Current situation
The current svFSIplus does not include interfaces for PETSc and Trilinos. 

## Release Notes 
The following features were added in this pull request:
- PETSc and Trilinos interfaces were implemented in svFSIplus by @ktbolt.
- in the folder Docker/, dockerfiles based on Ubuntu 20 and Ubuntu 22 images were created. The containers built from the dockerfiles, include pre-built PETSc and Trilinos libraries and related dependencies. This addresses #211. 
- in .github/workflows/ the file test_ubuntu.yml was created. This workflow file uses the pre-built libraries in the containers (see previous bullet point) to compile svFSIplus solver and run the tests. 
- the following tests are added to verify the PETSc and Trilinos implementation (test_fsi.py, test_fluid.py and conftest.py were modified accordingly): 
       fluid/: pipe_RCR_3d_petsc/ pipe_RCR_3d_ilut_trilinos/ pipe_RCR_3d_bj_trilinos/
       fsi/: pipe_3d_petsc/ pipe_3d_ml_trilinos/ pipe_3d_bj_trilinos

## Documentation
More information about the docker containers created refer to the following link:
https://hub.docker.com/repository/docker/dcodoni/lib/general

## Testing
All the tests ran successfully. The tests for PETSc and Trilinos were only run on Ubuntu, while MacOS skipped these tests.

## Code of Conduct & Contributing Guidelines 
- [x] I agree to follow the [Code of Conduct](https://github.com/SimVascular/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/SimVascular/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by MatteoSalvador — CHANGES_REQUESTED** [review]
Thank you @dcodoni, you did a fantastic job!

I think everything is fine except for a few things on the tests.
Specifically, I do not understand why `test_LV_NeoHookean_passive` and `test_LV_NeoHookean_passive_genBC` have been removed from `struct`/`ustruct` and why some linear solver settings for `cep` test cases (maximum number of iterations, tolerances, ...) have been changed.

**Comment by dcodoni** [comment]
Hello @MatteoSalvador, I did not remove or modify existent tests cases, I just added few cases. I do not know the reason of the mentioned modifications. I can check the differences and include them.

**Comment by ktbolt** [comment]
@dcodoni You should add a README to the `svFSIplus/Docker` directory describing how to use the containers and such. 

Why are there separate docker files (e.g. ubuntu20-on-mac-host) for MacOS ?

And why are you building VTK in the containers? It would be easier and take less time to just install it.

Are you planning on creating containers for MacOS and Windows? 

And be sure to update any relevant GitHub Issues related to Docker containers, I see three.

**Comment by dcodoni** [comment]
@ktbolt I will create a README file explaining how to use it, how to build a dockerfile and how to run a container.

 I will delete 'ubuntu*-on-mac-host' folders, they were a test I was doing locally on my laptop.

To build VTK from source requires time, so I decided to install everything needed to build the solver, in a container.
 
For the moment I am not thinking about creating containers for MacOS and Windows, since there are no images that recreates those OS that can be used as bases for the container. The closest functionality I found is an image that when run recreates the MacOS and can be used as a virtual machine. This can't be used in a dockerfile to create a container.

The issue #211 has been added by @MatteoSalvador.

**Review by ktbolt — APPROVED** [review]
Looks good!

**Pull request closed without merging**
