### PR TITLE
High order element face mesh fails 205

### PR DESCRIPTION
**Pull request by ktbolt**
CFD simulations were failing with 10-noded Tets, fixed several bugs. See https://github.com/SimVascular/svFSIplus/issues/205.

The PR has a bit of noise from adding some debugging statements and replacing some incorrect array initialization statements.

### CODE REVIEW

**Review by MatteoSalvador — CHANGES_REQUESTED** [review]
Thanks @ktbolt, I talked to @wgyang and he will kindly add a new test case to cover these new functions before merging the PR.

**Comment by MatteoSalvador** [comment]
@wgyang thanks for adding this test! Unfortunately the integration tests are currently failing with the error `No module named 'conftest'`. I think you should update `test_fluid.py` again with `from .conftest import run_with_reference` instead of `from conftest import run_with_reference`

**Comment by wgyang** [comment]
> @wgyang thanks for adding this test! Unfortunately the pipeline is currently failing with the error `No module named 'conftest'`. I think you should update `test_fluid.py` again with `from .conftest import run_with_reference` instead of `from conftest import run_with_reference`

@MatteoSalvador  Sorry about that. I will fix it.
Thank you!

**Comment by MatteoSalvador** [comment]
@wgyang I have changed the workflow for tests on Ubuntu to a Docker-based framework. If you pull the current `SimVascular/svFSIplus` we should be able to merge this.

**Comment by wgyang** [comment]
> @wgyang I have changed the workflow for tests on Ubuntu to a Docker-based framework. If you pull the current `SimVascular/svFSIplus` we should be able to merge this PR as well!

Thank you @MatteoSalvador! Will do.

**Comment by MatteoSalvador** [comment]
@ktbolt I noticed that this PR has been closed (and the corresponding branch deleted) before merging it.
Is there a specific reason for this?

**Comment by ktbolt** [comment]
@MatteoSalvador Did this not get merged by @wgyang.

**Comment by MatteoSalvador** [comment]
@ktbolt I think it was almost ready to be merged, but there were still a few minor issues for testing and CI was not running correctly.

@wgyang do you agree?

**Comment by wgyang** [comment]
@MatteoSalvador Yes, Yes, there were a few compatibility issues with a specific version of the operating system.

**Comment by MatteoSalvador** [comment]
Thanks @wgyang! Unfortunately, I cannot reopen this PR because the original branch has been deleted. Could you replicate all the features of this PR starting from the current main of svFSIplus? Otherwise I can of course help you with this!

**Comment by wgyang** [comment]
@MatteoSalvador I recreated a pull request in order to merge the fix for the high order element test case.

**Comment by MatteoSalvador** [comment]
Thanks @wgyang, the PR looks great!

**Pull request closed without merging**
