### PR TITLE
svZeroD Solver Coupling Interface

### PR DESCRIPTION
**Pull request by kharold23**
svZeroD Solver Coupling Interface

## Current situation
#70 

## Release Notes 
- Added integration with svZeroD solver to allow for 3D-0D coupling with sv0D
- Added test cases in fluid, struct, and ustruct
- Added sv0D build/compiling to the workflows to allow tests to run

## Documentation
 
*Please ensure that you properly document any additions.*

## Testing
*Please ensure that the PR meets the testing requirements set by GitHub Actions.*
 
*In addition, please ensure all modified and new code is covered by tests.*

## Code of Conduct & Contributing Guidelines 
- [x] I agree to follow the [Code of Conduct](https://github.com/SimVascular/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/SimVascular/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by MatteoSalvador — COMMENTED** [review]
Thanks @kharold23, great job!

I see there are only a few issues on Ubuntu and MacOS for continuous integration. For the former, you can have a chat with @dcodoni so he can properly integrate cloning and building `svZeroDSolver` into his docker containers (feel free to explore other options, of course). For the latter, it seems that the `genBC` related tests actually fail. Probably we should just upgrade them to `svZeroDSolver` without changing the reference solution (which should remain the same).

**Comment by kharold23** [comment]
Yep! I'm working with him now! Also, I have to check into the genBC tests, because they were working before I rebased my code.

**Comment by dcodoni** [comment]
Good job @kharold23! 
I have no comments from my part!

**Comment by kharold23** [comment]
Ok, I got all of the test cases working again! (I had to add the "Linear Algebra" element to the xml files and then decrease the tolerance for the ustruct case)

**Review by MatteoSalvador — APPROVED** [review]

**Pull request merged**
