### PR TITLE
Update Docker README.md

### PR DESCRIPTION
**Pull request by dcodoni**
Docker containers documentation updated to include the use of containers on an HPC system ( addresses #233 )

## Current situation
The present README.md file in Docker/ folder does not contain any information on how to use containers on HPC systems. It only describes how to use Docker software to build and execute Docker containers on a local machine.

## Documentation 
I added a new section on the README.md file describing how to pull a container from a public DockerHub repository, and how to execute the container using Singularity software (loaded by default on Sherlock).

## Code of Conduct & Contributing Guidelines 
- [x] I agree to follow the [Code of Conduct](https://github.com/SimVascular/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/SimVascular/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ktbolt** [comment]
@dcodoni You should not be working in your **main** branch.

**Comment by ktbolt** [comment]
@dcodoni The `How to use containers on an HPC system:` should be in the https://github.com/SimVascular/svFSIplus/blob/main/README.md file.

Also don't talk about Sherlock since only Stanford people know what that is. 

Most users will not want to build svFSIplus in a container. They will just want to download a container with a run-time image  to their HPC cluster. 

We will probably want to create a simvascular account on Docker Hub for our images.

**Comment by MatteoSalvador** [comment]
Thanks @dcodoni for all these important instructions on HPC systems!

However, I suggest following the two comments from @ktbolt before merging this PR.

**Comment by dcodoni** [comment]
Thanks @ktbolt for your feedback! 
I created this doc file quickly because many people were asking me about how to use containers on Sherlock, but I can close this pull request and make modifications on a branch. 
I will make these new modifications in https://github.com/SimVascular/svFSIplus/blob/main/README.md file. Should I add a new section in "getting started" (https://simvascular.github.io/svFSIplus/index.html)?

I created the containers just for automatic testing purposing. If there is a need to create a container with the executable only, it can be done. The problem with this is that an image must be created everytime the solver is updated. I may figure out something to automize this.

 I agree, we should create a DockerHub account for the group.

**Pull request closed without merging**
